import type { Metadata } from "next";
import "./globals.css";
import { WrapperQueryClientProvider } from "@/queryClientProvider/queryClientProvider";
import CookieBanner from "@/ui/components/cookiesPreference/cookiesPreference";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WrapperQueryClientProvider>
          {children}
          <CookieBanner />
        </WrapperQueryClientProvider>
      </body>
    </html>
  );
}
